version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
