version: '3'
services:
  backend:
    build:
      context: ./backend  # Updated to backend directory
      dockerfile: Dockerfile  # Adjust Dockerfile name if needed
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend/builderio  # Updated to frontend/builderio directory
      dockerfile: Dockerfile  # Adjust Dockerfile name if needed
    ports:
      - "3000:3000"
    env_file:
      - .env
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
